key = "value"
bare_key = "value"
bare-key = "value"
1234 = "value"
"127.0.0.1" = 3.14159
"character encoding" = "value"
"ʎǝʞ" = nan
'key2' = 213
'quoted "value"' = 1979-05-27T00:32:00.999999-07:00
name = "Orange"
physical.color = 'orange'
physical.shape = """

round

"""
site."google.com" = true
