"I'm a string. \"You can quote me\". Name\tJos\u00E9\nLocation\tSF."

"""
Roses are red \u0001f525
Violets are blue"""
""""This," she said, "is just a pointless statement \u0001f644.""""

'C:\Users\nodejs\templates'
'\\ServerX\admin$\system32\'
'Tom "Dubs" Preston-Werner'
'<\i\c*\s*>'

'''I [dw]on't need \d{2} apples'''
'''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
'''Here are fifteen quotation marks: """""""""""""""'''
''''That,' she said, 'is still pointless.''''

