           # this is a valid comment.
[package]
name = "tomlp"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-segmentation = "~1.11.0"
chrono = "0.4.38"

[lib]
name = "tomlp"
path = "src/lib.rs"

[[bin]]
name = "prototype"
    path = "src/bin.rs"


[[bin]]
name = 123
    path = "src/bin.rs"
