true
false
   true
        false
1979-05-27T00:32:00.999999-07:00
1.1233
0xAEF
0b11011101
-3.0e-27
+inf
    1979-05-27T00:32:00.999999
0o707
123445
    1979-05-27T07:32:00Z
-nan
    1979-05-27T00:32:00-07:00
1979-05-27T00:32:00    
1979-05-27 00:32:00.999999     
        1979-05-27 00:32:01
        1979-05-27
        07:32:00
00:32:00.999999
"I'm a string. \"You can quote me\". Name\tJos\u00E9\nLocation\tSF."
"""
Roses are red \u0001f525
Violets are blue"""
""""This," she said, "is just a pointless statement \u0001f644.""""
'C:\Users\nodejs\templates'
'\\ServerX\admin$\system32\'
'Tom "Dubs" Preston-Werner'
'<\i\c*\s*>'
'''I [dw]on't need \d{2} apples'''
'''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
'''Here are fifteen quotation marks: """""""""""""""'''
''''That,' she said, 'is still pointless.''''
